### ISSUE TITLE
CI Pipeline findet keine Tests

### ISSUE THREAD

**Issue by csknkdhbw** [sk1ldpadde/OMNISTUDYIN#9]
@sk1ldpadde Ich glaube es liegt wieder am Pfad, war bei mir in VS Code schon so, dass er keine Tests gefunden hat, wenn es in einem Unterordner war. Muss man mal schauen, was da das Problem ist.

**Comment by sk1ldpadde** [comment]
python -m unittest discover -s data_logic
     
sucht nach files, die dem Regex test* entsprechen. Demnach alle Tests mit test als Anfang benennen!
